### ISSUE TITLE
Impossible to close popups after features are destroyed

### ISSUE THREAD

**Issue by ZiglioUK** [volpino/openlayers-timeline#1]
Ciao Fox!

I've discovered a little problem, when the timebar changes and a popup is still open, the feature associated with that popup is destroyed, therefore making it impossible to close the popup.
I've made a number of changes in my repository but perhaps you could use my little routine that cycles through popups on the map:

var i;
for( i in self.map.popups ){
  var popup = self.map.popups[i];
  self.map.removePopup(popup);
  popup.selectedFeature.popup.destroy();
  popup = null;
}

I've also provided a kml format. The only problem I need to pass some options to inizialize it (to use Google Maps), so I initialize it before creating timeline, but that can be easily changed:

var in_options = {
  'internalProjection': map.baseLayer.projection,
   'externalProjection': new OpenLayers.Projection("EPSG:4326")
};

var kmlOptionsIn = OpenLayers.Util.extend({
  extractAttributes: true,
  extractStyles: true,
  extractTracks: true,
  trackAttributes: true,
  maxDepth: 2
}, in_options);

kmlformat = new OpenLayers.Format.KML(kmlOptionsIn);

```
  timeline = new OpenLayers.Timeline({map: map,
                            timeline: "#timeline",
                            date_key: "when",
                            format: kmlformat,
                            date_funct: function(date){
                              return date.getTime()/1000;
                            },
                            onFeatureInsert: updateLatestFix
                            });
```

Grazie mille!

**Comment by volpino** [comment]
Ciao Emanuele :D
I don't have the problem your are mentioning. On which browser do you work on? I use Firefox and everything seems ok! Could you please send me more details? If I click on a cluster, the popup appears, then if i go back or forward in time and the cluster is destroyed i can always close the popup with the red button.
The KML stuff is really cool, is it ok for you to send a pull request?

**Comment by ZiglioUK** [comment]
Uei!

With regards to this issue, at work I use Chrome for Linux, at home mainly Chrome but now I've managed to reproduce the problem on IE9 (Win7). At firsts I wasn't able to reproduce it using the time slider but then I played a bit with zooming in and out and ended up with popups alone without features. So, yeah, it sucks that OpenLayers doesn't destroy automatically child objects like popups but obviously it does sometimes so maybe it's a bug with OL. Let me know if you succeed in reproducing the bug.

Please, feel free to pull the changes (do you need a pull request? I'm new to GitHub :-)
Right now I'm trying to fix a problem with the 'cumulative' option. It's due to the order I rebuild the features in slider.change().
I've spent more than an hour trying to fix it yesterday without success...
What was the problem with 'projections' you mentioned on twitter?

I'd like to implement some improvements, like:
1. not having to parse the format over and over again during animations
2. a reverse time slider, that goes back in time (that should be easy to do).
3. ability to load more features when you reach the limit, a bit like infinite scrolling for tables.
4. ability to choose different strategies, other than cluster 

This could become a standard widget for OpenLayers, what do you think? but it'd be nice to having to modify the existing formats.

**Comment by volpino** [comment]
Uh! ok, i figured it out. You're saying it could happen that there's a popup without any feature associated. Anyway the popup can be closed with the close button.

At the moment I don't have so much time to work on this and I don't have any related project that could use this lib. But if you want to add some features and other cool stuff would be great!

**Comment by ZiglioUK** [comment]
If the feature is destroyed and the popup is still there, there's no way to close it because the close handler calls has disappeared.
I'll see if I can put a test together but my code loops through and closes all the popups before actually destroying features
